using Content.Client.UserInterface.Systems.Actions.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Actions.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ActionsBar : UIWidget
{
    public ActionsBar()
    {
        RobustXamlLoader.Load(this);

        var i = 1;
        ActionButton? last = null;

        foreach (var child in ActionsContainer.Children)
        {
            if (child is not ActionButton button)
                continue;

            button.Label.Text = $"{i}";

            last = button;
            i++;
        }

        if (last != null)
            last.Label.Text = "0";
    }
}

