- type: entity
  abstract: true
  parent: [SolutionCryo, SolutionCompositeNormalStackable, BaseItem]
  id: MaterialBase
  description: A raw material.
  components:
  - type: Appearance
  - type: Sprite
    sprite: Objects/Materials/materials.rsi
  - type: Item
    sprite: Objects/Materials/materials.rsi
    size: Normal
  - type: Material
  - type: Tag
    tags:
    - RawMaterial
  - type: Damageable
  - type: Injurable
    damageContainer: Inorganic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 100
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Extractable
    grindableSolutionName: composite

- type: entity
  abstract: true
  parent: MaterialBase
  id: BaseSheet
  components:
  - type: Tag
    tags:
    - Sheet
    - ConstructionMaterial
  - type: StaticPrice
    price: 0
