using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mapping;

[GenerateTypedNameReferences]
public sealed partial class MappingVisibilityWindow : DefaultWindow
{
    public MappingVisibilityWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

