using Content.Shared.FeedbackSystem;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.FeedbackPopup;

[GenerateTypedNameReferences]
public sealed partial class FeedbackEntry : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IUriOpener _uri = default!;

    private FeedbackPopupPrototype? _feedbackpopup;

    public FeedbackEntry()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(ProtoId<FeedbackPopupPrototype> popupProto)
    {
        _feedbackpopup = _proto.Index(popupProto);

        // Title
        TitleLabel.Text = _feedbackpopup.Title;
        DescriptionLabel.Text = _feedbackpopup.Description;

        // link button
        if (!string.IsNullOrEmpty(_feedbackpopup.ResponseLink))
        {
            LinkButton.OnPressed += OnButtonPressed;
        }
    }

    private void OnButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (_feedbackpopup?.ResponseLink != null)
            _uri.OpenUri(_feedbackpopup.ResponseLink);
    }

    protected override void Resized()
    {
        base.Resized();
        // magic
        TitleLabel.SetWidth = Width - TitleLabel.Margin.SumHorizontal;
        TitleLabel.InvalidateArrange();
        DescriptionLabel.SetWidth = Width - DescriptionLabel.Margin.SumHorizontal;
        DescriptionLabel.InvalidateArrange();
    }
}

