using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.UIWindows;

[GenerateTypedNameReferences]
public sealed partial class ActionsWindow : FancyWindow
{
    public ActionsWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
