- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconERTJanitor"
  supervisors: job-supervisors-centcom
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTJanitorGearEVA
  id: ERTJanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMagERT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
    suitstorage: WeaponLauncherHydra
  storage:
    back:
    - SoapNT
    - Plunger
    - Screwdriver
    - AdvMopItem
    - GrenadeCleanade
    - GrenadeCleanade # End of first line
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    belt:
    - MegaSprayBottleSpaceCleaner
    - Holoprojector
    - LightReplacerFilled
    - WireBrush
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen
  inhand:
    - TrashBag

- type: chameleonOutfit
  id: ERTJanitorChameleonOutfit
  job: ERTJanitor
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTJanitor
    neck: ClothingNeckScarfStripedPurple
    eyes: ClothingEyesGlassesSunglasses
