- type: cargoProduct
  id: SecurityArmor
  icon:
    sprite: Clothing/OuterClothing/Armor/bulletproof.rsi
    state: icon
  product: ClothingOuterArmorBulletproof
  container: CrateSecgear
  cost: 400
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityHelmet
  icon:
    sprite: Clothing/Head/Helmets/security.rsi
    state: icon
  product: ClothingHeadHelmetBasic
  container: CrateSecgear
  cost: 175
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityDisabler
  icon:
    sprite: Objects/Weapons/Guns/Battery/disabler.rsi
    state: base
  product: WeaponDisabler
  container: CrateSecgear
  cost: 500
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityStunBaton
  icon:
    sprite: Objects/Weapons/Melee/stunbaton.rsi
    state: stunbaton_off
  product: Stunbaton
  container: CrateSecgear
  cost: 500
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityFlashbang
  icon:
    sprite: Objects/Weapons/Grenades/flashbang.rsi
    state: icon
  product: BoxFlashbang
  container: CrateSecgear
  cost: 500
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityFlash
  icon:
    sprite: Objects/Weapons/Melee/flash.rsi
    state: flash
  product: Flash
  container: CrateSecgear
  cost: 200
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityHandcuff
  icon:
    sprite: Objects/Misc/handcuffs.rsi
    state: handcuff
  product: BoxHandcuff
  container: CrateSecgear
  cost: 200
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityHud
  icon:
    sprite: Clothing/Eyes/Hud/sec.rsi
    state: icon
  product: BoxSechud
  container: CrateSecgear
  cost: 200
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityZiptie
  icon:
    sprite: Objects/Misc/zipties.rsi
    state: cuff
  product: BoxZiptie
  container: CrateSecgear
  cost: 200
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityBiosuit
  icon:
    sprite: Clothing/Head/Hoods/Bio/security.rsi
    state: icon
  products:
  - ClothingOuterBioSecurity
  - ClothingHeadHatHoodBioSecurity
  container: CrateSecgear
  cost: 600
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityBarrier
  icon:
    sprite: Objects/Specific/Security/barrier.rsi
    state: idle
  product: DeployableBarrier
  cost: 1000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityStinger
  icon:
    sprite: Objects/Weapons/Grenades/stingergrenade.rsi
    state: icon
  product: BoxStinger
  container: CrateSecgear
  cost: 200
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityTearGas
  icon:
    sprite: Objects/Weapons/Grenades/tear_gas.rsi
    state: icon
  product: BoxTearGas
  container: CrateSecgear
  cost: 200
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityBola
  icon:
    sprite: Objects/Weapons/Throwable/bola.rsi
    state: icon
  product: Bola
  container: CrateSecgear
  cost: 200
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityGenPopCloset
  icon:
    sprite: Structures/Storage/closet.rsi
    state: genpop
  product: LockerPrisoner
  cost: 250
  category: cargoproduct-category-name-security
  group: market
