using System.Linq;
using System.Net.Mime;
using Content.Shared.CriminalRecords;
using Content.Shared.Security;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CriminalRecords;

[GenerateTypedNameReferences]
public sealed partial class GeneralCriminalRecordConsoleWindow : DefaultWindow
{
    public Action<StationRecordKey?>? OnKeySelected;
    private bool _isPopulating;
    public Action<BaseButton.ButtonEventArgs, string?, string?>? OnArrestButtonPressed;
    public Action<OptionButton.ItemSelectedEventArgs, SecurityStatus, string?, string?>? OnStatusOptionButtonSelected;
    private string? RecordName;

    public GeneralCriminalRecordConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        var itemIndex = 0;

        RecordListing.OnItemSelected += args =>
        {
            if (_isPopulating || RecordListing[args.ItemIndex].Metadata is not StationRecordKey cast)
            {
                return;
            }

            itemIndex = args.ItemIndex;
            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            if (!_isPopulating)
                OnKeySelected?.Invoke(null);
        };

        ArrestButton.OnPressed += e => OnArrestButtonPressed?.Invoke(e, ReasonLineEdit.Text, RecordName);

        StatusOptionButton.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            OnStatusOptionButtonSelected?.Invoke(args, (SecurityStatus) StatusOptionButton.GetItemMetadata(args.Id)!,
                ReasonLineEdit.Text, RecordName);
        };

    }

    public void UpdateState(GeneralCriminalRecordConsoleState state)
    {
        if (state.RecordListing == null)
        {
            RecordListingStatus.Visible = true;
            RecordListing.Visible = false;
            RecordListingStatus.Text = Loc.GetString("general-station-record-console-empty-state");
            return;
        }

        RecordListingStatus.Visible = false;
        RecordListing.Visible = true;
        PopulateRecordListing(state.RecordListing!, state.SelectedKey);

        RecordContainerStatus.Visible = state.CriminalRecord == null;

        ReasonLineEdit.Visible = state.SelectedKey != null;
        ArrestButton.Visible = state.SelectedKey != null;
        CriminalDivider.Visible = state.SelectedKey != null;
        StatusOptionButton.Visible = state.SelectedKey != null;

        StatusOptionButton.Disabled = state.CriminalRecord?.Status == SecurityStatus.Detained;

        if (state.CriminalRecord != null & state.StationRecord != null)
        {
            ReasonLineEdit.Visible = state.SelectedKey != null;
            ArrestButton.Visible = state.SelectedKey != null;
            CriminalDivider.Visible = state.SelectedKey != null;
            StatusOptionButton.Visible = state.SelectedKey != null;

            StatusOptionButton.Disabled = state.CriminalRecord?.Status == SecurityStatus.Detained;

            if (!StatusOptionButton.Disabled)
            {
                StatusOptionButton.Clear();

                var id_none = AddStatusSelect("None", SecurityStatus.None);
                if (SecurityStatus.None == state.CriminalRecord?.Status)
                    StatusOptionButton.Select(id_none);

                var id_wanted = AddStatusSelect("Wanted", SecurityStatus.Wanted);
                if (SecurityStatus.Wanted == state.CriminalRecord?.Status)
                    StatusOptionButton.Select(id_wanted);
            }
            else
                StatusOptionButton.AddItem("Detained");

            RecordContainerStatus.Visible = state.SelectedKey == null;
            RecordContainerStatus.Text = state.SelectedKey != null
                ? Loc.GetString("general-station-record-console-no-record-found")
                : Loc.GetString("general-station-record-console-select-record-info");
            RecordName = state.StationRecord?.Name;
            PopulateRecordContainer(state.StationRecord!, state.CriminalRecord!);
        }
        else
        {
            RecordContainer.DisposeAllChildren();
            RecordContainer.RemoveAllChildren();
        }
    }

    private void PopulateRecordListing(Dictionary<StationRecordKey, string> listing, StationRecordKey? selected)
    {
        RecordListing.Clear();
        RecordListing.ClearSelected();

        _isPopulating = true;
        foreach (var (key, name) in listing)
        {
            var item = RecordListing.AddItem(name);
            item.Metadata = key;

            if (selected != null && key.ID == selected.Value.ID)
            {
                item.Selected = true;
            }
        }
        _isPopulating = false;

        RecordListing.SortItemsByText();
    }

    private void PopulateRecordContainer(GeneralStationRecord stationRecord, GeneralCriminalRecord criminalRecord)
    {
        RecordContainer.DisposeAllChildren();
        RecordContainer.RemoveAllChildren();
        // sure

        var recordControls = new Control[]
        {
            new Label()
            {
                Text = stationRecord.Name,
                StyleClasses = { "LabelBig" }
            },
            new Label()
            {
                Text = Loc.GetString("general-station-record-console-record-age", ("age", stationRecord.Age.ToString()))

            },
            new Label()
            {
                Text = Loc.GetString("general-station-record-console-record-title", ("job", Loc.GetString(stationRecord.JobTitle)))
            },
            new Label()
            {
                Text = Loc.GetString("general-station-record-console-record-species", ("species", stationRecord.Species))
            },
            new Label()
            {
                Text = Loc.GetString("general-station-record-console-record-gender", ("gender", stationRecord.Gender.ToString()))
            },
            new Label()
            {
                Text = Loc.GetString("general-station-record-console-record-fingerprint", ("fingerprint", stationRecord.Fingerprint is null ? Loc.GetString("generic-not-available-shorthand") : stationRecord.Fingerprint))
            },
            new Label()
            {
                Text = $"Status: {criminalRecord.Status.ToString()}" // TODO: make it colorful
            }
        };

        foreach (var control in recordControls)
        {
            RecordContainer.AddChild(control);
        }

        if (criminalRecord.Reason != string.Empty)
        {
            var label = new Label()
            {
                Text = criminalRecord.Reason
            };
            RecordContainer.AddChild(label);
        }
    }

    private int AddStatusSelect(string name, SecurityStatus status)
    {
        StatusOptionButton.AddItem(name);
        StatusOptionButton.SetItemMetadata(StatusOptionButton.ItemCount - 1, status);
        return StatusOptionButton.ItemCount - 1;
    }
}
