using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Revenant.Ui;

[GenerateTypedNameReferences]
public sealed partial class RevenantListingControl : Control
{
    public RevenantListingControl(string itemName, string itemDescription,
        int itemPrice, bool canBuy, Texture? texture = null)
    {
        RobustXamlLoader.Load(this);

        RevenantItemName.Text = itemName;
        RevenantItemDescription.SetMessage(itemDescription);

        RevenantItemBuyButton.Text = Loc.GetString("revenant-user-interface-cost", ("price", itemPrice));
        RevenantItemBuyButton.Disabled = !canBuy;

        RevenantItemTexture.Texture = texture;
    }
}
