#!/usr/bin/env bash

gitroot=$(git rev-parse --show-toplevel)


if [[ $(uname) == MINGW* || $(uname) == CYGWIN* ]]; then
    # Windows
    py -3 "$gitroot/BuildChecker/git_helper.py" --quiet
else
    # Not Windows, so probably some other Unix thing.
    python3 "$gitroot/BuildChecker/git_helper.py" --quiet
fi

