using System.Diagnostics;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Robust.Roslyn.Shared;

namespace Content.Shared.GuidebookGenerator;

[Generator]
public sealed class Generator : IIncrementalGenerator
{
    private const string Component = "Robust.Shared.GameObjects.Component";
    private const string GuidebookDataAttribute = "Content.Shared.Guidebook.GuidebookDataAttribute";
    private const string GuidebookDataInterface = "Content.Shared.Guidebook.IGuidebookData";

    public void Initialize(IncrementalGeneratorInitializationContext initContext)
    {
        var comps = initContext
            .SyntaxProvider
            .CreateSyntaxProvider<(string file, IndentWriter source)?>(
                static (node, _) => node is ClassDeclarationSyntax,
                static (context, cancel) =>
                {
                    var type = (TypeDeclarationSyntax)context.Node;
                    if (context.SemanticModel.GetDeclaredSymbol(type, cancel) is not INamedTypeSymbol symbol)
                        return null;

                    if (!TypeSymbolHelper.Inherits(symbol, Component))
                        return null;

                    var guidebookFields = TypeSymbolHelper
                        .GetAllMembersIncludingInherited(symbol)
                        .Where(m => AttributeHelper.HasAttribute(m, GuidebookDataAttribute))
                        .ToList();

                    if (guidebookFields.Count == 0)
                        return null;

                    var info = PartialTypeInfo.FromSymbol(symbol, type);
                    var hasParent = TypeSymbolHelper
                        .GetBaseTypes(symbol)
                        .Any(s => s.GetMembers().Any(m => AttributeHelper.HasAttribute(m, GuidebookDataAttribute)));

                    var modifiers = hasParent
                        ? "override "
                        : info.IsSealed
                            ? string.Empty
                            : "virtual ";

                    var sb = new IndentWriter(new StringBuilder());
                    sb.AppendLine("// <auto-generated />");
                    sb.AppendLine();

                    info.WriteHeader(ref sb);

                    sb.PopDepth();
                    sb.Append($" : global::{GuidebookDataInterface}");
                    sb.AppendLine();
                    sb.AppendOpeningBrace();

                    sb.AppendLineIndented($"public {modifiers}global::System.Collections.Generic.IEnumerable<string> GetFieldNames()");
                    sb.AppendOpeningBrace();

                    foreach (var field in guidebookFields)
                    {
                        sb.AppendLineIndented($"""yield return "{field.Name}";""");
                    }

                    sb.AppendClosingBrace();
                    sb.AppendLine();

                    sb.AppendLineIndented($"public {modifiers}object GetFieldValue(string name)");
                    sb.AppendOpeningBrace();

                    sb.AppendLineIndented("return name switch");
                    sb.AppendOpeningBrace();

                    foreach (var field in guidebookFields)
                    {
                        sb.AppendLineIndented($"\"{field.Name}\" => this.{field.Name},");
                    }

                    sb.AppendLineIndented("""_ => throw new global::System.ArgumentException($"No field found with name {name}"),""");

                    sb.PopDepth();
                    sb.AppendLineIndented("};");
                    sb.AppendClosingBrace();
                    sb.AppendClosingBrace();

                    info.WriteFooter(ref sb);

                    var file = info.GetGeneratedFileName();
                    return (file, sb);
                }
            )
            .Where(static type => type != null);

        initContext.RegisterSourceOutput(
            comps,
            static (context, tuple) =>
            {
                var (file, source) = tuple!.Value;
                context.AddSource(file, source.ToString());
            }
        );
    }
}
