# DS14 CBURN and DBCT GEAR

### Leader
### CBURN
- type: job
  id: CBURNLeader
  name: job-name-cburn-leader
  description: job-description-cburnleader
  playTimeTracker: JobCBURNLeader
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 144000 # 40 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 288000 # 80 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 144000 # 40 hours
    - !type:OverallPlaytimeRequirement
      time: 3096000 # 860 hours
  startingGear: CBURNLeaderGear
  icon: "JobIconERTLeader"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - ErtTeamLeader
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: CBURNLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    mask: ClothingMaskGasExplorer
    eyes: ClothingEyesHudAdvanced
    ears: ClothingHeadsetAltAERT
    neck: ClothingNeckMantleCBURNLeaderShoulder
    gloves: ClothingHandsGlovesCombat
    back: ClothingMilitaryBackpackCBURNLeader
    belt: ClothingBeltMilitaryWebbingCBURNLeader
    outerClothing: ClothingOuterHardsuitCBURNLeader
    suitstorage: JetpackSecurityFilled
    shoes: ClothingShoesBootsMagHos
    id: CBURNLeaderPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: DoorRemoteCustom


### SCST
- type: job
  id: SCSTLeader
  name: job-name-scst-leader
  description: job-description-cburnleader
  playTimeTracker: JobSCSTLeader
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 144000 # 40 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 288000 # 80 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 144000 # 40 hours
    - !type:OverallPlaytimeRequirement
      time: 3096000 # 860 hours
  startingGear: SCSTLeaderGear
  icon: "JobIconERTLeader"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - ErtTeamLeader
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: SCSTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    mask: ClothingMaskGasExplorer
    eyes: ClothingEyesHudAdvanced
    ears: ClothingHeadsetAltAERT
    neck: ClothingNeckMantleCBURNLeaderShoulder
    gloves: ClothingHandsGlovesCombat
    back: ClothingMilitaryBackpackCBURNSpiderLeader
    belt: ClothingBeltMilitaryWebbingCBURNSpiderLeader
    outerClothing: ClothingOuterHardsuitCBURNSCSTLeader
    suitstorage: JetpackSecurityFilled
    shoes: ADTClothingShoesBootsMagERT
    id: CBURNLeaderPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: DoorRemoteCustom


### SCNT
- type: job
  id: SCNTLeader
  name: job-name-scnt-leader
  description: job-description-cburnleader
  playTimeTracker: JobSCNTLeader
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 144000 # 40 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 288000 # 80 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 144000 # 40 hours
    - !type:OverallPlaytimeRequirement
      time: 3096000 # 860 hours
  startingGear: SCNTLeaderGear
  icon: "JobIconERTLeader"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - ErtTeamLeader
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: SCNTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    mask: ClothingMaskGasExplorer
    eyes: ClothingEyesHudAdvanced
    ears: ClothingHeadsetAltAERT
    neck: ClothingNeckMantleCBURNLeaderShoulder
    gloves: ClothingHandsGlovesCombat
    back: ClothingMilitaryBackpackCBURNNecroLeader
    belt: ClothingBeltMilitaryWebbingCBURNNecroLeader
    outerClothing: ClothingOuterHardsuitCBURNNECROLeader
    suitstorage: JetpackSecurityFilled
    shoes: ADTClothingShoesBootsMagERT
    id: CBURNLeaderPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: DoorRemoteCustom

### Sierra
- type: job
  id: SierraLeader
  name: job-name-sierra-leader
  description: job-description-cburnleader
  playTimeTracker: JobSierraLeader
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 144000 # 40 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 288000 # 80 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 144000 # 40 hours
    - !type:OverallPlaytimeRequirement
      time: 3096000 # 860 hours
  startingGear: SierraLeaderGear
  icon: "JobIconERTLeader"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - ErtTeamLeader
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: SierraLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    mask: ClothingMaskGasExplorer
    eyes: ClothingEyesGlassesThermalVisor
    head: ClothingHeadHatBeretCentcomNaval
    ears: ClothingHeadsetAltAERT
    neck: ClothingNeckMantleCBURNLeaderShoulder
    gloves: ClothingHandsGlovesCombat
    back: ClothingMilitaryBackpackCBURNSierraLeader
    belt: ClothingBeltMilitaryWebbingCBURNSierra
    outerClothing: ClothingOuterHardsuitCBURNLeader
    suitstorage: JetpackVoidFilled
    shoes: ADTClothingShoesBootsMagERT
    id: CBURNLeaderPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: DoorRemoteCustom

### Agent
### CBURN
- type: job
  id: CBURNAgent
  name: job-name-cburn-agent
  description: job-description-cburnagent
  playTimeTracker: JobCBURNAgent
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 57600 # 16 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 201600 # 56 hours
    - !type:OverallPlaytimeRequirement
      time: 3096000 # 860 hours
  startingGear: CBURNAgentGear
  icon: "JobIconERT"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: CBURNAgentGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    mask: ClothingMaskGasExplorer
    eyes: ClothingEyesHudAdvanced
    ears: ClothingHeadsetAltAERT
    gloves: ClothingHandsGlovesCombat
    back: ClothingMilitaryBackpackCBURN
    belt: ClothingBeltMilitaryWebbingCBURN
    outerClothing: ClothingOuterHardsuitCBURN
    suitstorage: JetpackSecurityFilled
    shoes: ClothingShoesBootsMagSecurity
    id: CBURNPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: FlashlightSeclite

### SCST
- type: job
  id: SCSTAgent
  name: job-name-scst-agent
  description: job-description-cburnagent
  playTimeTracker: JobSCSTAgent
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 57600 # 16 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 201600 # 56 hours
    - !type:OverallPlaytimeRequirement
      time: 3096000 # 860 hours
  startingGear: CBURNAgentGear
  icon: "JobIconERT"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: SCSTAgentGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    mask: ClothingMaskGasExplorer
    eyes: ClothingEyesHudAdvanced
    ears: ClothingHeadsetAltAERT
    gloves: ClothingHandsGlovesCombat
    back: ClothingMilitaryBackpackCBURNSpider
    belt: ClothingBeltMilitaryWebbingCBURNSpider
    outerClothing: ClothingOuterHardsuitCBURNSCSTSoldier
    suitstorage: JetpackSecurityFilled
    shoes: ADTClothingShoesBootsMagERT
    id: CBURNPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: TelescopicShield

### SCNT
- type: job
  id: SCNTAgent
  name: job-name-scnt-agent
  description: job-description-cburnagent
  playTimeTracker: JobSCNTAgent
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 57600 # 16 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 201600 # 56 hours
    - !type:OverallPlaytimeRequirement
      time: 3096000 # 860 hours
  startingGear: SCNTAgentGear
  icon: "JobIconERT"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: SCNTAgentGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    mask: ClothingMaskGasExplorer
    eyes: ClothingEyesHudAdvanced
    ears: ClothingHeadsetAltAERT
    gloves: ClothingHandsGlovesCombat
    back: ClothingMilitaryBackpackCBURNNecro
    belt: ClothingBeltMilitaryWebbingCBURNNecro
    outerClothing: ClothingOuterHardsuitCBURNNECROSoldier
    suitstorage: JetpackSecurityFilled
    shoes: ADTClothingShoesBootsMagERT
    id: CBURNPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: TelescopicShield

### Sierra
- type: job
  id: SierraAgent
  name: job-name-sierra-agent
  description: job-description-cburnagent
  playTimeTracker: JobSierraAgent
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 57600 # 16 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 201600 # 56 hours
    - !type:OverallPlaytimeRequirement
      time: 3096000 # 860 hours
  startingGear: SierraAgentGear
  icon: "JobIconERT"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: SierraAgentGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    mask: ClothingMaskGasExplorer
    eyes: ClothingEyesHudERTGamma
    head: ClothingHeadHatBeretMerc
    ears: ClothingHeadsetAltAERT
    gloves: ClothingHandsGlovesCombat
    back: ClothingMilitaryBackpackCBURNSierra
    belt: ClothingBeltMilitaryWebbingCBURNSierra
    outerClothing: ClothingOuterHardsuitCBURN
    suitstorage: JetpackVoidFilled
    shoes: ADTClothingShoesBootsMagERT
    id: CBURNPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: TelescopicShield

# Other
- type: entity
  parent: ClothingNeckMantleHOSShoulder
  id: ClothingNeckMantleCBURNLeaderShoulder
  name: наплечная мантия командира отряда ОБХУ
  description: Мантия отличающая командира отряда из Отделения Био-Химических Угроз.
  components:
  - type: Sprite
    sprite: Clothing/Neck/mantles/hosmantle_shoulder.rsi
  - type: Clothing
    sprite: Clothing/Neck/mantles/hosmantle_shoulder.rsi

- type: entity
  parent: PillCanister
  id: PillCanisterCBURN
  name: баночка для таблеток
  description: Содержит пять таблеток амбузола. Часть стандартного снаряжения члена РХБЗЗ.
  suffix: Амбузол, РХБЗЗ
  components:
  - type: StorageFill
    contents:
    - id: PillAmbuzol
      amount: 5
