# Зелёный Берет
- type: job
  id: CentralCommandGreenBeretOfficer
  name: job-name-green-beret-officer
  description: job-description-green-beret-officer
  playTimeTracker: JobCentralCommandGreenBeretOfficer
  setPreference: false
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 252000 # 70 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
  startingGear: CentcomGreenBeretGear
  icon: "JobIconGreenBeretOfficer"
  supervisors: job-supervisors-centcom-administrator
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: ZombieImmune
    - type: NpcFactionMember
      factions:
      - CentralCommand

- type: entity
  parent: BasePDA
  id: GreenBeretOfficerPDA
  components:
  - type: Pda
    id: GreenBeretOfficerIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-ert
  - type: PdaBorderColor
    borderColor: "#12445b"
    accentHColor: "#772d32"
    accentVColor: "#772d32"
  - type: Icon
    state: pda-ert
  - type: HealthAnalyzer
    scanDelay: 1
  - type: ErtTrackerPda
    allowedDepartments:
    - SpecialOperationsCorps
    allowedJobs:
    - BlueShieldOfficer
    - CentralCommandGreenBeretOfficer
    - CentralCommandSpecialOperationsOfficer

- type: entity
  parent: IDCardStandard
  id: GreenBeretOfficerIDCard
  components:
    - type: Sprite
      layers:
        - state: default
        - state: ert_security
    - type: PresetIdCard
      job: CentralCommandGreenBeretOfficer

- type: entity
  parent: ClothingBackpack
  id: ClothingBackpackGreenBeret
  name: модифицированный рюкзак офицера "Зелёный Берет"
  description: Рюкзак офицера "Зелёный Берет" с функцией РИГ.
  components:
  - type: Sprite
    sprite: _DeadSpace/Clothing/Back/greenberet.rsi
  - type: Storage
    grid:
    - 0,0,7,5
  - type: ClothingSpeedModifier
    walkModifier: 1
    sprintModifier: 1
  - type: ToggleableClothing
    toggleDelay: 1
    clothingPrototype: ClothingOuterHardsuitGreenBeret
    requiredSlot: BACK
    slot: outerClothing
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
  - type: ContainerContainer
    containers:
      toggleable-clothing: !type:ContainerSlot {}
      storagebase: !type:Container
        ents: []
  - type: StorageFill
    contents:
      - id: ERTloadoutBlueShieldPrimary
      - id: HandheldCrewMonitor
  - type: ExplosionResistance
    damageCoefficient: 0.6

- type: startingGear
  id: CentcomGreenBeretGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGreenBeret
    back: ClothingBackpackGreenBeret
    neck: ClothingNeckMantleGreenBerethoulder
    eyes: ClothingEyesHudGreenBeret
    head: ClothingHeadHatBeretGreenBeret
    mask: ClothingMaskGasGreenBeret
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesGreenBeret
    outerClothing: ClothingOuterArmorGreenBeret
    shoes: ClothingShoesBootsGreenBeret
    id: GreenBeretOfficerPDA
    pocket1: FlashlightSeclite
    pocket2: WeaponDisabler
    belt: ClothingBeltMilitaryWebbingRedSwordCentComFilled
  storage:
    back:
    - BoxCardboardERT
    - ERTloadoutBlueShieldPrimary
    - ADTtelescopicBaton
    - TelescopicShield
    - MedkitCombatFilled
    - MedkitCombatFilled
    - HandheldCrewMonitor
    - Zipties
    - Zipties
    - Zipties
    - CelestinMedipen
    - CelestinMedipen
    - CelestinMedipen
    - CelestinMedipen

- type: chameleonOutfit
  id: CentcomGreenBeretGearChameleonOutfit
  job: CentralCommandGreenBeretOfficer
  equipment:
    head: ClothingHeadHatBeretBlueShield
    mask: ClothingMaskGasSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicBlueShield
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltMilitaryWebbingMed

# Красный Меч
- type: job
  id: CentralCommandRedSwordOfficer
  name: job-name-red-sword-officer
  description: job-description-red-sword-officer
  playTimeTracker: JobCentralCommandRedSwordOfficer
  setPreference: false
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 252000 # 70 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
  startingGear: CentcomRedSwordGear
  icon: "JobIconRedSwordOfficer"
  supervisors: job-supervisors-centcom-administrator
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: ZombieImmune
    - type: NpcFactionMember
      factions:
      - CentralCommand

- type: entity
  parent: BasePDA
  id: RedSwordOfficerPDA
  components:
  - type: Pda
    id: RedSwordOfficerIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-ert
  - type: PdaBorderColor
    borderColor: "#12445b"
    accentHColor: "#772d32"
    accentVColor: "#772d32"
  - type: Icon
    state: pda-ert
  - type: HealthAnalyzer
    scanDelay: 1
  - type: ErtTrackerPda
    allowedDepartments:
    - SpecialOperationsCorps
    allowedJobs:
    - BlueShieldOfficer
    - CentralCommandGreenBeretOfficer
    - CentralCommandSpecialOperationsOfficer
    - CentralCommandRedSwordOfficer

- type: entity
  parent: IDCardStandard
  id: RedSwordOfficerIDCard
  components:
    - type: Sprite
      layers:
        - state: default
        - state: ert_security
    - type: PresetIdCard
      job: CentralCommandRedSwordOfficer

- type: startingGear
  id: CentcomRedSwordGear
  equipment:
    jumpsuit: ClothingUniformTurtleneckTactic
    # back: ClothingBackpackSatchelBig
    neck: ClothingNeckMantleRedSwordhoulder
    eyes: ClothingEyesHudERTGamma
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitRedSword
    shoes: ADTClothingShoesBootsMagERT
    id: RedSwordOfficerPDA
    pocket1: FlashlightSeclite
    pocket2: WeaponDisabler
    belt: ClothingBeltMilitaryWebbingRedSwordCentComFilled
  storage:
    back:
    - BoxCardboardERT
    - ERTloadoutGammaPrimary
    - BSAACombatKitFilled
    - PinpointerNuclear
    - InjectorCaseERTFilled
    - TelescopicShield
    - TelescopicShield

- type: chameleonOutfit
  id: CentcomRedSwordGearChameleonOutfit
  job: CentralCommandRedSwordOfficer
  equipment:
    head: ClothingHeadHatBeretBlueShield
    mask: ClothingMaskGasSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicBlueShield
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltMilitaryWebbingMed