using Content.Server.Nodes.EntitySystems.Autolinkers;
using Content.Shared.Nodes;

namespace Content.Server.Nodes.Components.Autolinkers;

/// <summary>
/// A graph node autoconnector component that forms connections between anchored nodes on the same tile.
/// Behaviour is handled by <see cref="PortNodeSystem"/>
/// </summary>
[Access(typeof(PortNodeSystem))]
[RegisterComponent]
public sealed partial class PortNodeComponent : Component
{
    /// <summary>
    /// Whether this autoconnector can form and/or maintain links with other nodes.
    /// </summary>
    [DataField("connectionsEnabled")]
    [ViewVariables(VVAccess.ReadWrite)]
    public bool ConnectionsEnabled = true;

    /// <summary>
    /// The tag that the other node must have in order for this to link to it. If omitted it will form links with _every_ anchored node on the same tile.
    /// </summary>
    [DataField("tag")]
    [ViewVariables(VVAccess.ReadWrite)]
    public string? Tag = null;

    /// <summary>
    /// The edge flags applied to any edge generated by this autoconnector.
    /// </summary>
    [DataField("flags")]
    [ViewVariables(VVAccess.ReadWrite)]
    public EdgeFlags Flags = EdgeFlags.None;
}
