# When adding a new board game, also add it to id: AllBoardGamesTable

# Note: all board game pieces should be marked as HideSpawnMenu, they lack most of the physical components for practical use.

# The actual item that players can pick up, or throw when they lose
- type: entity
  abstract: true
  parent: BaseItem
  id: BaseBoardEntity # Board item
  name: board
  description: A blank board.
  components:
  - type: TabletopGame
    size: 256, 256
    setup:
      !type:TabletopEmptySetup
      boardPrototype: Crowbar
  - type: Tag
    tags:
    - TabletopBoard

- type: entity
  abstract: true
  id: BaseTabletopPiece # Board piece
  components:
  - type: TabletopDraggable
  - type: Sprite
    noRot: true
  - type: Appearance
  - type: Clickable
  - type: InteractionOutline

# Entity which acts as the background sprite in the tabletop game
- type: entity
  abstract: true
  id: BaseBoardTabletop
  name: baseboard
  components:
  - type: Sprite
    noRot: false
    drawdepth: FloorTiles
