- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ReporterGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    id: LibrarianPDA
    ears: ClothingHeadsetSecurity
    pocket1: BaseUplinkRadioCT # for BATTLE
    belt: ClothingBeltMilitaryWebbing
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ReporterChameleonOutfit
  job: Reporter
  equipment:
    head: ClothingHeadHatFedoraGrey
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterCoatTrench
    neck: ClothingNeckTieRed
    gloves: ClothingHandsGlovesFingerless
