- type: job
  id: TramDriver
  name: job-name-tram-driver
  description: job-description-tram-driver
  playTimeTracker: JobTramDriver
  startingGear: TramDriverGear
  icon: "JobIconTramDriver"
  supervisors: job-supervisors-hop
  requirements:
    - !type:OverallPlaytimeRequirement # someone that's not doing this job will just be a pain for the station
      time: 10h
  access:
  - Maintenance
  - Command
  - Service
  - External # to pick up people trapped in the tramway's space
  special: # we don't want it becoming an antag... for now at least
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: TramDriverGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: TramDriverPDA
    ears: ClothingHeadsetService
 # storage:
 #   back:
 #  - RubberStampPsychologist

- type: chameleonOutfit
  id: TramDriverChameleonOutfit
  job: TramDriver
  equipment:
    head: ClothingHeadHatBeretMedic
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    outerClothing: ClothingOuterCoatLab
    neck: ClothingNeckStethoscope
    belt: ClothingBeltMedical
    gloves: ClothingHandsGlovesLatex
