using System.Linq;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class MessagerCartridgeUiFragment : BoxContainer
{
    private int _currentChatPartnerId;
    private Dictionary<int, MessagerUserEntry> _users = new();

    public MessagerCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        SendButton.OnPressed += OnSendPressed;
        BackButton.OnPressed += OnBackPressed;
        MessageInput.OnTextEntered += OnMessageInputSubmit;
    }

    public void UpdateState(MessagerStatus status, Dictionary<int, MessagerUserEntry> users, List<MessagerMessageEntry>? messages = null)
    {
        _users = users ?? new Dictionary<int, MessagerUserEntry>();

        ConnectingContainer.Visible = status == MessagerStatus.Connecting;
        ConnectedContainer.Visible = status == MessagerStatus.Connected;
        ConnectionLostContainer.Visible = status == MessagerStatus.ConnectionLost;

        // Update user list
        UserListContainer.RemoveAllChildren();
        foreach (var user in _users.Values)
        {
            var button = new Button { Text = user.Name, HorizontalExpand = true };
            var userId = user.Id;
            button.OnPressed += _ => OnUserSelected(userId);
            UserListContainer.AddChild(button);
        }

        if (messages != null && messages.Count > 0 && !MainScreenContainer.Visible)
        {
            UpdateMessages(messages);
        }
    }

    private void OnUserSelected(int userId)
    {
        _currentChatPartnerId = userId;

        if (_users.TryGetValue(userId, out var user))
        {
            ChatPartnerLabel.Text = user.Name;
        }

        MainScreenContainer.Visible = false;
        MessageInputContainer.Visible = true;

        // Request messages from server
        OnRequestMessages?.Invoke(userId);
    }

    private void OnBackPressed(BaseButton.ButtonEventArgs args)
    {
        MessageInputContainer.Visible = false;
        MainScreenContainer.Visible = true;
        _currentChatPartnerId = 0;
    }

    private void OnSendPressed(BaseButton.ButtonEventArgs args)
    {
        SendMessage();
    }

    private void OnMessageInputSubmit(LineEdit.LineEditEventArgs args)
    {
        SendMessage();
    }

    private void SendMessage()
    {
        var text = MessageInput.Text.Trim();
        if (string.IsNullOrEmpty(text) || _currentChatPartnerId == 0)
            return;

        OnSendMessage?.Invoke(_currentChatPartnerId, text);
        MessageInput.Clear();
    }

    private void UpdateMessages(List<MessagerMessageEntry> messages)
    {
        MessageContainer.RemoveAllChildren();

        var filteredMessages = messages.Where(m =>
            m.SenderId == _currentChatPartnerId || m.ReceiverId == _currentChatPartnerId);

        foreach (var msg in filteredMessages.OrderBy(m => m.Timestamp))
        {
            var label = new Label
            {
                Text = $"{msg.SenderName}: {msg.Content}",
                HorizontalExpand = true,
                FontColorOverride = msg.IsIncoming ? Color.Aqua : Color.White
            };
            MessageContainer.AddChild(label);
        }
    }

    public event Action<int, string>? OnSendMessage;
    public event Action<int>? OnRequestMessages;
}
