//
// Copyright (C) 1993-1996 Id Software, Inc.
// Copyright (C) 2019-2020 Nobuaki Tanaka
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//



using System;

namespace ManagedDoom
{
    public enum Sprite
    {
        TROO,
        SHTG,
        PUNG,
        PISG,
        PISF,
        SHTF,
        SHT2,
        CHGG,
        CHGF,
        MISG,
        MISF,
        SAWG,
        PLSG,
        PLSF,
        BFGG,
        BFGF,
        BLUD,
        PUFF,
        BAL1,
        BAL2,
        PLSS,
        PLSE,
        MISL,
        BFS1,
        BFE1,
        BFE2,
        TFOG,
        IFOG,
        PLAY,
        POSS,
        SPOS,
        VILE,
        FIRE,
        FATB,
        FBXP,
        SKEL,
        MANF,
        FATT,
        CPOS,
        SARG,
        HEAD,
        BAL7,
        BOSS,
        BOS2,
        SKUL,
        SPID,
        BSPI,
        APLS,
        APBX,
        CYBR,
        PAIN,
        SSWV,
        KEEN,
        BBRN,
        BOSF,
        ARM1,
        ARM2,
        BAR1,
        BEXP,
        FCAN,
        BON1,
        BON2,
        BKEY,
        RKEY,
        YKEY,
        BSKU,
        RSKU,
        YSKU,
        STIM,
        MEDI,
        SOUL,
        PINV,
        PSTR,
        PINS,
        MEGA,
        SUIT,
        PMAP,
        PVIS,
        CLIP,
        AMMO,
        ROCK,
        BROK,
        CELL,
        CELP,
        SHEL,
        SBOX,
        BPAK,
        BFUG,
        MGUN,
        CSAW,
        LAUN,
        PLAS,
        SHOT,
        SGN2,
        COLU,
        SMT2,
        GOR1,
        POL2,
        POL5,
        POL4,
        POL3,
        POL1,
        POL6,
        GOR2,
        GOR3,
        GOR4,
        GOR5,
        SMIT,
        COL1,
        COL2,
        COL3,
        COL4,
        CAND,
        CBRA,
        COL6,
        TRE1,
        TRE2,
        ELEC,
        CEYE,
        FSKU,
        COL5,
        TBLU,
        TGRN,
        TRED,
        SMBT,
        SMGT,
        SMRT,
        HDB1,
        HDB2,
        HDB3,
        HDB4,
        HDB5,
        HDB6,
        POB1,
        POB2,
        BRS1,
        TLMP,
        TLP2,
        Count
    }
}
