using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.UserInterface.Systems.Medical.Controls;

[GenerateTypedNameReferences]
public sealed partial class BodyPartEntry : BoxContainer
{
}
