using Content.Shared._Starlight.MassDriver;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.MassDriver.UI;

[GenerateTypedNameReferences]
public sealed partial class MassDriverConsoleMenu : DefaultWindow
{
    public MassDriverConsoleMenu() => RobustXamlLoader.Load(this);

    public void UpdateState(MassDriverUiState state)
    {
        
    }
}