using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client.HealthAnalyzer.UI.Tooltips;

[GenerateTypedNameReferences]
[Virtual]
public partial class UpdatableTooltip : PanelContainer
{
    public UpdatableTooltip()
    {
        RobustXamlLoader.Load(this);
    }

    public virtual void Update(HealthAnalyzerScannedUserMessage msg)
    {
    }
}
