using System.Collections.Generic;
using System.Text;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;
using Robust.Shared.Log;
using Content.Client.Message;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Content.Shared.Atmos.Components;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using System;
using System.Diagnostics;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BoxContainer;



using static Content.Shared.CloningConsole.SharedCloningConsoleComponent;

namespace Content.Client.CloningConsole.UI
{
    [GenerateTypedNameReferences]
    public partial class CloningConsoleWindow : DefaultWindow
    {
        public CloningConsoleWindow()
        {
            RobustXamlLoader.Load(this);

        }
        private CloningConsoleBoundUserInterfaceState? _lastUpdate;
        private List<string> _historyManager = default!;

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            UpdateProgress();
        }

        private void UpdateProgress()
        {
            if (_lastUpdate == null)
                return;
            float simulatedProgress = _lastUpdate.Progress;
            if (_lastUpdate.Progressing)
            {
                TimeSpan sinceReference = IoCManager.Resolve<IGameTiming>().CurTime - _lastUpdate.ReferenceTime;
                simulatedProgress += (float) sinceReference.TotalSeconds;
                simulatedProgress = MathHelper.Clamp(simulatedProgress, 0f, _lastUpdate.Maximum);
            }
            var percentage = simulatedProgress / CloningProgressBar.MaxValue * 100;
            ProgressLabel.Text = $"{percentage:0}%";
            CloningProgressBar.Value = simulatedProgress;
        }

        private void BuildHistory()
        {
            HistoryList.RemoveAllChildren();

            foreach (var historyItem in _historyManager)
            {
                var historyRowItem = new HistoryRow
                {
                  CloneName = historyItem
                };
                historyRowItem.EntityLabel.Text = historyItem;

                HistoryList.AddChild(historyRowItem);
            }
        }

        public void Populate(CloningConsoleBoundUserInterfaceState state)
        {
            // BUILD CLONING HISTORY
            if (_lastUpdate == null || _lastUpdate.CloneHistory.Count != state.CloneHistory.Count)
            {
                _historyManager = state.CloneHistory;
                if (_historyManager == null)
                {
                    _historyManager = new List<string>();
                }
                BuildHistory();
            }
            _lastUpdate = state;

            // BUILD SCANNER UI
            if (state.ScannerConnected)
            {
                GeneticScannerContents.Visible = true;
                GeneticScannerMissing.Visible = false;

                if (state.ScannerBodyInfo != null)
                {
                    ScannerInfoLabel.SetMarkup(Loc.GetString("cloning-console-window-scanner-id",
                    ("scannerOccupantName", state.ScannerBodyInfo)));
                } else
                {
                    ScannerInfoLabel.SetMarkup(Loc.GetString("cloning-console-window-id-blank"));
                }
                CloneButton.Disabled = !state.ReadyToClone;
            }
            else
            {
                GeneticScannerContents.Visible = false;
                GeneticScannerMissing.Visible = true;
            }
            // BUILD ClONER UI
            if (state.ClonerConnected)
            {
                CloningPodContents.Visible = true;
                CloningPodMissing.Visible = false;

                CloningProgressBar.MinSize = (200, 20);
                CloningProgressBar.MinValue = 0;
                CloningProgressBar.MaxValue = 120;
                CloningProgressBar.Page = 0;
                CloningProgressBar.Value = 0.5f;
                CloningProgressBar.MaxValue = state.Maximum;
                UpdateProgress();

                ClonerBrainActivity.Text = Loc.GetString(state.MindPresent ? "cloning-console-mind-present-text" : "cloning-console-no-mind-activity-text");
                ClonerBrainActivity.FontColorOverride = state.MindPresent ? Color.LimeGreen : Color.Red;

                if (state.ClonerBodyInfo != null)
                {
                    ClonerInfoLabel.SetMarkup(Loc.GetString("cloning-console-window-pod-id",
                    ("podOccupantName", state.ClonerBodyInfo)));
                } else
                {
                    ClonerInfoLabel.SetMarkup(Loc.GetString("cloning-console-window-id-blank"));
                }
            } else
            {
                CloningPodContents.Visible = false;
                CloningPodMissing.Visible = true;
            }
        }

        [DebuggerDisplay("cloninghistory {" + nameof(Index) + "}")]
        private class HistoryRow : Control
        {
            public string CloneName { get; set; } = default!;
            public Label EntityLabel { get; private set; }
            public TextureRect EntityTextureRect { get; private set; }
            public int Index { get; set; }

            public HistoryRow()
            {
                AddChild(new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Children =
                    {
                        (EntityTextureRect = new TextureRect
                        {
                            MinSize = (32, 32),
                            HorizontalAlignment = HAlignment.Center,
                            VerticalAlignment = VAlignment.Center,
                            Stretch = TextureRect.StretchMode.KeepAspectCentered,
                            CanShrink = true
                        }),
                        (EntityLabel = new Label
                        {
                            VerticalAlignment = VAlignment.Center,
                            HorizontalExpand = true,
                            Text = string.Empty,
                            ClipText = true
                        })
                    }
                });
            }
        }
    }
}
