using Content.Shared.BluespaceHarvester;
using Robust.Shared.Audio;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization.TypeSerializers.Implementations.Custom.Prototype;

namespace Content.Server.BluespaceHarvester;

[RegisterComponent]
public sealed partial class BluespaceHarvesterComponent : Component
{
    public bool Reseted = false;

    /// <summary>
    /// The current level at which the harvester is located is what other parameters are calculated from.
    /// </summary>
    [DataField, ViewVariables(VVAccess.ReadWrite)]
    public int CurrentLevel = 0;

    /// <summary>
    /// The level to which the harvester always strives if possible. It is installed by the player, but during the reset, this feature is blocked.
    /// </summary>
    [DataField, ViewVariables(VVAccess.ReadWrite)]
    public int TargetLevel = 0;

    /// <summary>
    /// The level above which it is impossible not to set TargetLevel.
    /// </summary>
    [DataField]
    public int MaxLevel = 20;

    /// <summary>
    /// The level above which the Danger begin to rise.
    /// </summary>
    [DataField]
    public int StableLevel = 10;

    /// <summary>
    /// Similar to StableLevel, but replaces it when hacked by a Emag.
    /// </summary>
    [DataField]
    public int EmaggedStableLevel = 5;

    /// <summary>
    /// Points generated by harvesters, which can be spent on purchasing things in categories.
    /// </summary>
    [DataField, ViewVariables(VVAccess.ReadWrite)]
    public int Points = 0;

    /// <summary>
    /// Displays how many points have been generated, regardless of spending.
    /// </summary>
    [DataField, ViewVariables(VVAccess.ReadWrite)]
    public int TotalPoints = 0;

    [DataField]
    public BluespaceHarvesterVisuals RedspaceTap = BluespaceHarvesterVisuals.TapRedspace;

    [DataField]
    public float SpawnRadius = 5f;

    [DataField, ViewVariables(VVAccess.ReadWrite)]
    public int Danger = 0;

    /// <summary>
    /// After this danger value, the generation of dangerous creatures and anomalies will begin.
    /// </summary>
    [DataField]
    public int DangerLimit = 175;

    /// <summary>
    /// Tries once every 1 second, with this chance to create a rift if DangerLimit is exceeded.
    /// </summary>
    [DataField]
    public float RiftChance = 0.1f;

    /// <summary>
    /// Replaces RiftChance when hacked by Emag.
    /// </summary>
    [DataField]
    public float EmaggedRiftChance = 0.05f;

    [DataField, ViewVariables(VVAccess.ReadWrite)]
    public EntProtoId Rift = "BluespaceHarvesterRift";

    [DataField]
    public List<BluespaceHarvesterCategoryInfo> Categories = new()
    {
        new BluespaceHarvesterCategoryInfo()
        {
            PrototypeId = "RandomHarvesterBiologicalLoot",
            Cost = 7_500,
            Type = BluespaceHarvesterCategory.Biological,
        },
        new BluespaceHarvesterCategoryInfo()
        {
            PrototypeId = "RandomHarvesterTechnologicalLoot",
            Cost = 10_000,
            Type = BluespaceHarvesterCategory.Technological,
        },
        new BluespaceHarvesterCategoryInfo()
        {
            PrototypeId = "RandomHarvesterIndustrialLoot",
            Cost = 12_500,
            Type = BluespaceHarvesterCategory.Industrial,
        },
        new BluespaceHarvesterCategoryInfo()
        {
            PrototypeId = "RandomHarvesterDestructionLoot",
            Cost = 15_000,
            Type = BluespaceHarvesterCategory.Destruction,
        },
    };

    [DataField, ViewVariables(VVAccess.ReadWrite)]
    public EntProtoId SpawnEffect = "EffectEmpPulse";

    [DataField, ViewVariables(VVAccess.ReadWrite)]
    public SoundSpecifier SpawnSound = new SoundPathSpecifier("/Audio/Effects/teleport_arrival.ogg");
}

[Serializable]
public sealed partial class BluespaceHarvesterTap
{
    [DataField]
    public int Level;

    [DataField]
    public BluespaceHarvesterVisuals Visual;
}
