using Content.Client.UserInterface.Controls;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Preferences.UI;

[GenerateTypedNameReferences]
public sealed partial class LoadoutWindow : FancyWindow
{
    public LoadoutWindow(RoleLoadoutPrototype proto, IPrototypeManager protoManager)
    {
        RobustXamlLoader.Load(this);

        foreach (var group in proto.Groups)
        {
            var container = new LoadoutGroupContainer(protoManager.Index(group), protoManager);
            LoadoutGroupsContainer.AddChild(container);
        }
    }
}
