using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.PDA
{
    [GenerateTypedNameReferences]
    public partial class PDAMenu : SS14Window
    {
        public PDAMenu()
        {
            RobustXamlLoader.Load(this);

            MasterTabContainer.SetTabTitle(0, Loc.GetString("pda-bound-user-interface-main-menu-tab-title"));
        }
    }
}
