book-text-clown-law = Of the many inexplicable things in the galaxy, the clowns I count chief among them. One would expect a culture so chaotic to be more fragile. But clowns not only survive, they thrive. Countless aspects of the clown defy common sense. Their religion: famous for having the shortest holy text of all formal religions, and their laws: equally concise. To quote Clown Law in its entirety; “If it’s funny it’s legal.”

      Surely that’s not all. Police? Courts? There must be some aspect that enforces and interrogates bad actors. Nothing so systemic. Instead law is enforced entirely by the citizens, impromptu at the moment of capture, overseen by anyone nearby who chooses to attend. Clown court is now in session.

      Discard any ideas you have of the courts you’re familiar with. There is no judge or prosecutor. No Jury. It may as well be a mob, surrounding the “defendant” and anyone willing to act as defense. Alleged victims of the crime are treated no different than any other in attendance. Anyone can take the stage to offer testimony at any time, and yet this never devolves into a screaming mob.

      Clown court is strikingly somber. The cacophony of bike horns goes quiet, and whoopie cushions are saved for only the most poignant of moments. Clowns display a serious attitude rarely seen from their kind. The phrase, “explaining the joke ruins the joke,” comes to mind. But despite the tone, this event is none-the-less absurd. “Slapstick coefficient,” “honkology,” and other technical terms that make no sense to non-clowns are frequent. “Lawyers” for the accused hold no loyalty, and will switch sides many times. Victims of a crime will frequently act in defense of the perpetrator. And the conclusion - the punishment - is chaos.

      There is no authority on guilt in clown court. Instead, every clown in attendance decides for themselves if the crime was funny. It can get ugly. Clowns believe that everything is funnier when done to an unfunny person. A clown found guilty of being unfunny is subject to immediate tomfoolery, which can go on for days. Sometimes justice is so harsh I dare not describe it. Sometimes only a few clowns in attendance find fault, leading to disagreements on the punishment given, and more often than not clown court starts all over again.

      What is truly remarkable about it all is that it works. Donk Co. is a powerhouse in the market, with products desired across conflicts. Honkhome reports impossibly low rates of violent crime (definition of “violent” notwithstanding). Factories and farms function at peak efficiency due to a belief that damaging infrastructure isn’t funny. Theft is funny, and so ownership on Honkhome is a mere suggestion.

      Law affects so much of a culture that there’s no end to examples. What’s clear is that despite our differences, clown culture is as capable of industry and innovation as anyone else. So the next time you encounter a clown brazenly breaking the law, understand this: clowns do respect the law. To them, the law works. It is your laws they don’t respect.
