using System.Diagnostics;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

/// <summary>
/// A toggle button with a lock icon meant to lock values for randomizing in the character editor screen.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RandomizeLockButton : TextureButton
{
    /// <summary>
    /// Which value the randomize locking should apply for?
    /// </summary>
    public HumanoidCharacterProfile.RandomizeConfig For { get; set; }

    /// <summary>
    /// Stores current randomizer config.
    /// </summary>
    public static HumanoidCharacterProfile.RandomizeConfig RandomizeConfig = HumanoidCharacterProfile.RandomizeConfigAll;

    public RandomizeLockButton()
    {
        RobustXamlLoader.Load(this);

        const string lockTexture = "/Textures/Interface/VerbIcons/lock.svg.192dpi.png";
        const string unlockTexture = "/Textures/Interface/VerbIcons/unlock.svg.192dpi.png";
        OnToggled += args =>
        {
            if (For != default)
            {
                if (Pressed)
                {
                    // if pressed, disable randomize by setting bit 0
                    Log.Info("Pressed, new value (pre): " + RandomizeConfig);
                    RandomizeConfig &= ~For;
                    Log.Info("Pressed, new value: " + RandomizeConfig);
                    Log.Info("Pressed, new value: " +  (byte)RandomizeConfig);
                }
                else
                {
                    // if not pressed, enable randomize by setting bit 1
                    Log.Info("Unpressed, new value (pre): " + RandomizeConfig);
                    RandomizeConfig |= For;
                    Log.Info("Unpressed, new value: " + RandomizeConfig);
                }
                TexturePath = lockTexture;
            }
            else
            {
                TexturePath = unlockTexture;
            }
        };
        TexturePath = unlockTexture;
        Pressed = false;
    }
}

