//
// Copyright (C) 1993-1996 Id Software, Inc.
// Copyright (C) 2019-2020 Nobuaki Tanaka
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//



using System;

namespace ManagedDoom
{
    public enum Sfx
    {
        NONE,
        PISTOL,
        SHOTGN,
        SGCOCK,
        DSHTGN,
        DBOPN,
        DBCLS,
        DBLOAD,
        PLASMA,
        BFG,
        SAWUP,
        SAWIDL,
        SAWFUL,
        SAWHIT,
        RLAUNC,
        RXPLOD,
        FIRSHT,
        FIRXPL,
        PSTART,
        PSTOP,
        DOROPN,
        DORCLS,
        STNMOV,
        SWTCHN,
        SWTCHX,
        PLPAIN,
        DMPAIN,
        POPAIN,
        VIPAIN,
        MNPAIN,
        PEPAIN,
        SLOP,
        ITEMUP,
        WPNUP,
        OOF,
        TELEPT,
        POSIT1,
        POSIT2,
        POSIT3,
        BGSIT1,
        BGSIT2,
        SGTSIT,
        CACSIT,
        BRSSIT,
        CYBSIT,
        SPISIT,
        BSPSIT,
        KNTSIT,
        VILSIT,
        MANSIT,
        PESIT,
        SKLATK,
        SGTATK,
        SKEPCH,
        VILATK,
        CLAW,
        SKESWG,
        PLDETH,
        PDIEHI,
        PODTH1,
        PODTH2,
        PODTH3,
        BGDTH1,
        BGDTH2,
        SGTDTH,
        CACDTH,
        SKLDTH,
        BRSDTH,
        CYBDTH,
        SPIDTH,
        BSPDTH,
        VILDTH,
        KNTDTH,
        PEDTH,
        SKEDTH,
        POSACT,
        BGACT,
        DMACT,
        BSPACT,
        BSPWLK,
        VILACT,
        NOWAY,
        BAREXP,
        PUNCH,
        HOOF,
        METAL,
        CHGUN,
        TINK,
        BDOPN,
        BDCLS,
        ITMBK,
        FLAME,
        FLAMST,
        GETPOW,
        BOSPIT,
        BOSCUB,
        BOSSIT,
        BOSPN,
        BOSDTH,
        MANATK,
        MANDTH,
        SSSIT,
        SSDTH,
        KEENPN,
        KEENDT,
        SKEACT,
        SKESIT,
        SKEATK,
        RADIO
    }
}
