//
// Copyright (C) 1993-1996 Id Software, Inc.
// Copyright (C) 2019-2020 Nobuaki Tanaka
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//



using System;

namespace ManagedDoom
{
    public enum MobjType
    {
        Player,
        Possessed,
        Shotguy,
        Vile,
        Fire,
        Undead,
        Tracer,
        Smoke,
        Fatso,
        Fatshot,
        Chainguy,
        Troop,
        Sergeant,
        Shadows,
        Head,
        Bruiser,
        Bruisershot,
        Knight,
        Skull,
        Spider,
        Baby,
        Cyborg,
        Pain,
        Wolfss,
        Keen,
        Bossbrain,
        Bossspit,
        Bosstarget,
        Spawnshot,
        Spawnfire,
        Barrel,
        Troopshot,
        Headshot,
        Rocket,
        Plasma,
        Bfg,
        Arachplaz,
        Puff,
        Blood,
        Tfog,
        Ifog,
        Teleportman,
        Extrabfg,
        Misc0,
        Misc1,
        Misc2,
        Misc3,
        Misc4,
        Misc5,
        Misc6,
        Misc7,
        Misc8,
        Misc9,
        Misc10,
        Misc11,
        Misc12,
        Inv,
        Misc13,
        Ins,
        Misc14,
        Misc15,
        Misc16,
        Mega,
        Clip,
        Misc17,
        Misc18,
        Misc19,
        Misc20,
        Misc21,
        Misc22,
        Misc23,
        Misc24,
        Misc25,
        Chaingun,
        Misc26,
        Misc27,
        Misc28,
        Shotgun,
        Supershotgun,
        Misc29,
        Misc30,
        Misc31,
        Misc32,
        Misc33,
        Misc34,
        Misc35,
        Misc36,
        Misc37,
        Misc38,
        Misc39,
        Misc40,
        Misc41,
        Misc42,
        Misc43,
        Misc44,
        Misc45,
        Misc46,
        Misc47,
        Misc48,
        Misc49,
        Misc50,
        Misc51,
        Misc52,
        Misc53,
        Misc54,
        Misc55,
        Misc56,
        Misc57,
        Misc58,
        Misc59,
        Misc60,
        Misc61,
        Misc62,
        Misc63,
        Misc64,
        Misc65,
        Misc66,
        Misc67,
        Misc68,
        Misc69,
        Misc70,
        Misc71,
        Misc72,
        Misc73,
        Misc74,
        Misc75,
        Misc76,
        Misc77,
        Misc78,
        Misc79,
        Misc80,
        Misc81,
        Misc82,
        Misc83,
        Misc84,
        Misc85,
        Misc86
    }
}
