using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Info;

[GenerateTypedNameReferences]
public sealed partial class InfoControlsSection : BoxContainer
{
    public InfoControlsSection()
    {
        RobustXamlLoader.Load(this);
    }
}
