- type: job
  id: Janitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  startingGear: JanitorGear
  icon: "JobIconJanitor"
  supervisors: job-supervisors-hop
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: JanitorGear
  equipment:
    id: LibrarianPDA
    ears: ClothingHeadsetSecurity
    pocket1: BaseUplinkRadioCT # for making named bestsellers
    jumpsuit: ClothingUniformJumpsuitFSB
    head: ClothingHeadHatBalaklava
    belt: ClothingBeltMilitaryWebbing
    shoes: ClothingShoesBootsCombatFilled

