#!/usr/bin/env -i bash

# cd to file containing script or something?
BASEDIR=$(dirname "$0")
echo "$BASEDIR"
cd "$BASEDIR"

/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono ../Resources/SS14.Client.exe
