using System.Linq;
using Content.Shared.Atmos;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Content.Shared.Atmos.Components.GasAnalyzerComponent;

namespace Content.Client.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class GasAnalyzerControl : BoxContainer
{
    public GasAnalyzerControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(GasMixEntry gasMix)
    {
        TableKey.RemoveAllChildren();
        TableValue.RemoveAllChildren();
        TablePercent.RemoveAllChildren();
        BarChart.Clear();

        bool hasGas = (gasMix.Pressure > Atmospherics.GasMinMoles);

        // Volume, pressure, temperature
        VolumeLabel.Text = Loc.GetString("gas-analyzer-window-volume-val-text",
                                         ("volume", $"{gasMix.Volume:0.##}"));
        PressureLabel.Text = Loc.GetString("gas-analyzer-window-pressure-val-text",
                                           ("pressure", $"{gasMix.Pressure:0.00}"));
        TemperatureLabel.Text = "N/A";  // TODO translation

        if (hasGas)
        {
            var celsius = TemperatureHelpers.KelvinToCelsius(gasMix.Temperature);
            TemperatureLabel.Text =
                Loc.GetString("gas-analyzer-window-temperature-val-text",
                              ("tempK", $"{gasMix.Temperature:0.0}"),
                              ("tempC", $"{celsius:0.0}"));
        }

        // Empty placeholder, table, bar chart
        NoGasText.Visible = !hasGas;
        Table.Visible = hasGas;
        BarChart.Visible = hasGas;

        if (!hasGas || gasMix.Gases == null)
            return;

        var totalGasAmount = gasMix.Gases.Sum(gas => gas.Amount);

        foreach (var gas in gasMix.Gases)
        {
            var color = Color.FromHex($"#{gas.Color}", Color.White);
            var percent = gas.Amount / totalGasAmount * 100;
            var nameText = Loc.GetString(gas.Name);
            var valueText = Loc.GetString("gas-analyzer-window-molarity-text",
                                          ("mol", $"{gas.Amount:0.00}"));
            var percentText = Loc.GetString("gas-analyzer-window-percentage-text",
                                            ("percentage", $"{percent:0.0}"));
            var tooltip = Loc.GetString("gas-analyzer-window-molarity-percentage-text",
                                        ("gasName", gas.Name),
                                        ("amount", $"{gas.Amount:0.##}"),
                                        ("percentage", $"{percent:0.#}"));

            TableKey.AddChild(new Label { Text = nameText });
            TableValue.AddChild(new Label { Text = valueText, Align = Label.AlignMode.Right });
            TablePercent.AddChild(new Label { Text = percentText, Align = Label.AlignMode.Right });
            BarChart.AddEntry(gas.Amount, color, tooltip: tooltip);
        }
    }
}
