using System.Linq;
using System.Numerics;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using static Content.Shared.Atmos.Components.GasAnalyzerComponent;

namespace Content.Client.Atmos.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GasAnalyzerWindow : DefaultWindow
    {
        private static readonly Vector2 WindowMinSize = new Vector2(270, 350);
        private const float WindowMinHeightForScrollbar = 620;

        private NetEntity _currentEntity = NetEntity.Invalid;

        public GasAnalyzerWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void Populate(GasAnalyzerUserMessage msg)
        {
            DeviceName.InvalidateMeasure();  // "Just OK" workaround for a layout engine bug
            InvalidateMeasure();

            // Errors
            if (msg.Error != null)
            {
                ErrorText.Text = Loc.GetString("gas-analyzer-window-error-text", ("errorText", msg.Error));
                return;
            }

            if (msg.NodeGasMixes.Length == 0)
            {
                ErrorText.Text = Loc.GetString("gas-analyzer-window-no-data");
                return;
            }

            // Environment tab
            var envMix = msg.NodeGasMixes[0];
            Tabs.SetTabTitle(1, envMix.Name);
            EnvironmentMix.Populate(envMix);

            // Device tab
            DeviceMixes.RemoveAllChildren();
            bool hasDeviceTab = (msg.NodeGasMixes.Length > 1);
            Tabs.SetTabVisible(0, hasDeviceTab);

            if (!hasDeviceTab)
            {
                // There are no device mixes. Show only the environment mix.
                Tabs.CurrentTab = 1;
                _currentEntity = NetEntity.Invalid;
                return;
            }

            var device = IoCManager.Resolve<IEntityManager>().GetEntity(msg.DeviceUid);
            var deviceName = Loc.GetString("gas-analyzer-window-tab-title-capitalized", ("title", msg.DeviceName));
            DeviceIcon.SetEntity(device);
            DeviceName.Text = deviceName;
            Tabs.SetTabTitle(0, deviceName);

            // When the user targets a new device, switch to the device mix tab.
            if (_currentEntity != msg.DeviceUid)
            {
                Tabs.CurrentTab = 0;
                _currentEntity = msg.DeviceUid;
            }

            // Maximum of two mixes side-by-side. Any more mixes go on a new row.
            var mixCount = msg.NodeGasMixes.Length - 1;
            DeviceMixes.Columns = Math.Max(1, ((mixCount - 1) % 2) + 1);
            DeviceMixes.Rows = Math.Max(1, ((mixCount - 1) / 2) + 1);


            var deviceMixes = msg.NodeGasMixes.Skip(1);
            if (msg.DeviceFlipped)
                deviceMixes = deviceMixes.Reverse();

            foreach (var mix in deviceMixes)
            {
                var outlinePanel = new PanelContainer
                {
                    HorizontalAlignment = HAlignment.Center,
                    VerticalExpand = true,
                    Margin = new Thickness(4),
                    PanelOverride = new StyleBoxFlat
                    {
                        BorderThickness = new Thickness(1),
                        BorderColor = Color.FromHex("#4f4f4f")
                    }
                };

                var vbox = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    VerticalExpand = true
                };

                var nameLabel = new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-tab-title-capitalized", ("title", mix.Name)),
                    Align = Label.AlignMode.Center,
                    HorizontalExpand = true
                };

                var spacer = new Control { MinHeight = 12 };

                var gasAnalysis = new GasAnalyzerControl { Margin = new Thickness(8) };
                gasAnalysis.Populate(mix);

                vbox.AddChild(nameLabel);
                vbox.AddChild(spacer);
                vbox.AddChild(gasAnalysis);
                outlinePanel.AddChild(vbox);
                DeviceMixes.AddChild(outlinePanel);
            }
        }

        protected override Vector2 MeasureCore(Vector2 availableSize)
        {
            // Note that we override MeasureCore instead of MeasureOverride because we want to recalculate the minimum
            // and maximum size on the fly rather than making them constants. (Also resizable windows with a MaxSize are
            // very broken at the time of writing so we have to do it ourselves)

            var size = MeasureOverride(availableSize);
            if (!float.IsNaN(SetWidth) && !float.IsNaN(SetHeight))
                size = SetSize;

            // Here we make sure that the DesiredSize of the tabs is initialized to a reasonable size, but we invalidate
            // it again afterwards so that it will still be calculated the normal way.
            EnvironmentTabContent.Measure(availableSize);
            DevicesTabContents.Measure(availableSize);
            EnvironmentTabContent.InvalidateMeasure();
            DevicesTabContents.InvalidateMeasure();

            // The size of the window is the size of the bigger tab, but allowing for a scrollbar if the height is
            // greater than WindowMinHeightForScrollbar.
            var tab1Size = EnvironmentTabContent.DesiredSize;
            var tab2Size = DevicesTabContents.DesiredSize;
            var contentSize = Vector2.Max(tab1Size, tab2Size)
                              + new Vector2(50, 100);  // Extra space for margins, tabs and scrollbar.

            var maxSize = Vector2.Max(WindowMinSize, contentSize);
            var minSize = maxSize with { Y = Math.Min(maxSize.Y, WindowMinHeightForScrollbar) };
            return Vector2.Clamp(size, minSize, maxSize);
        }

        protected override Vector2 ArrangeOverride(Vector2 finalSize)
        {
            // The correct window size is exactly DesiredSize.
            return base.ArrangeOverride(DesiredSize);
        }
    }
}
