using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry.Components;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Chemistry.UI.ChemMaster
{
    /// <summary>
    /// Client-side UI used to control a <see cref="ChemMasterComponent"/>
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class ChemMasterWindow : FancyWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;

        private readonly SpriteSystem _sprite;

        public event Action<ReagentId, FixedPoint2, bool>? OnReagentButtonPressed;
        public readonly Button[] PillTypeButtons;

        private const string PillsRsiPath = "/Textures/Objects/Specific/Chemistry/pills.rsi";

        private readonly ReagentList _bufferReagentList;
        private readonly ReagentList _inputReagentList;
        private readonly ReagentList _outputReagentList;

        private ChemMasterSortingType? _lastSortingType;

        /// <summary>
        /// Create and initialize the chem master UI client-side. Creates the basic layout,
        /// actual data isn't filled in until the server sends data about the chem master.
        /// </summary>
        public ChemMasterWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _sprite = _entityManager.System<SpriteSystem>();

            // Pill type selection buttons, in total there are 20 pills.
            // Pill rsi file should have states named as pill1, pill2, and so on.
            var resourcePath = new ResPath(PillsRsiPath);
            var pillTypeGroup = new ButtonGroup();
            PillTypeButtons = new Button[20];
            for (uint i = 0; i < PillTypeButtons.Length; i++)
            {
                // For every button decide which stylebase to have
                // Every row has 10 buttons
                String styleBase = StyleBase.ButtonOpenBoth;
                uint modulo = i % 10;
                if (i > 0 && modulo == 0)
                    styleBase = StyleBase.ButtonOpenRight;
                else if (i > 0 && modulo == 9)
                    styleBase = StyleBase.ButtonOpenLeft;
                else if (i == 0)
                    styleBase = StyleBase.ButtonOpenRight;

                // Generate buttons
                PillTypeButtons[i] = new Button
                {
                    Access = AccessLevel.Public,
                    StyleClasses = { styleBase },
                    MaxSize = new Vector2(42, 28),
                    Group = pillTypeGroup
                };

                // Generate buttons textures
                var specifier = new SpriteSpecifier.Rsi(resourcePath, "pill" + (i + 1));
                TextureRect pillTypeTexture = new TextureRect
                {
                    Texture = _sprite.Frame0(specifier),
                    TextureScale = new Vector2(1.75f, 1.75f),
                    Stretch = TextureRect.StretchMode.KeepCentered,
                };

                PillTypeButtons[i].AddChild(pillTypeTexture);
                Grid.AddChild(PillTypeButtons[i]);
            }

            PillDosage.InitDefaultButtons();
            PillNumber.InitDefaultButtons();
            BottleDosage.InitDefaultButtons();

            // Ensure label length is within the character limit.
            LabelLineEdit.IsValid = s => s.Length <= SharedChemMaster.LabelMaxLength;

            Tabs.SetTabTitle(0, Loc.GetString("chem-master-window-input-tab"));
            Tabs.SetTabTitle(1, Loc.GetString("chem-master-window-output-tab"));

            // Initial reagent list setup
            _bufferReagentList = new ReagentList(Loc.GetString("chem-master-window-buffer-label") + " ",
                ChemMasterComponent.ChemMasterAmountOptions,
                Loc.GetString("chem-master-window-buffer-empty-text"));

            _inputReagentList = new ReagentList(Loc.GetString("chem-master-window-no-container-loaded-text"),
                ChemMasterComponent.ChemMasterAmountOptions);

            _outputReagentList = new ReagentList(Loc.GetString("chem-master-window-no-container-loaded-text"),
                []);

            BufferInfo.AddChild(_bufferReagentList);
            InputContainerInfo.AddChild(_inputReagentList);
            OutputContainerInfo.AddChild(_outputReagentList);

            _bufferReagentList.OnRowAmountPressed +=
                (id, quantity) => OnReagentButtonPressed?.Invoke(id, quantity, true);
            _inputReagentList.OnRowAmountPressed +=
                (id, quantity) => OnReagentButtonPressed?.Invoke(id, quantity, false);
        }

        /// <summary>
        /// Update the UI state when new state data is received from the server.
        /// </summary>
        /// <param name="state">State data sent by the server.</param>
        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (ChemMasterBoundUserInterfaceState)state;

            if (castState.UpdateLabel)
                LabelLine = GenerateLabel(castState);

            // Ensure the Panel Info is updated, including UI elements for Buffer Volume, Output Container and so on
            UpdatePanelInfo(castState);

            BufferCurrentVolume.Text = " " + ReagentQuantity.LocalizedQuantity(castState.BufferCurrentVolume);

            InputEjectButton.Disabled = castState.InputContainerInfo is null;
            OutputEjectButton.Disabled = castState.OutputContainerInfo is null;
            CreateBottleButton.Disabled = castState.OutputContainerInfo?.Reagents == null;
            CreatePillButton.Disabled = castState.OutputContainerInfo?.Entities == null;

            UpdateDosageFields(castState);
        }

        //assign default values for pill and bottle fields.
        private void UpdateDosageFields(ChemMasterBoundUserInterfaceState castState)
        {
            var output = castState.OutputContainerInfo;
            var remainingCapacity = output is null ? 0 : (output.MaxVolume - output.CurrentVolume).Int();
            var holdsReagents = output?.Reagents != null;
            var pillNumberMax = holdsReagents ? 0 : remainingCapacity;
            var bottleAmountMax = holdsReagents ? remainingCapacity : 0;
            var bufferVolume = castState.BufferCurrentVolume?.Int() ?? 0;

            PillDosage.Value = (int)Math.Min(bufferVolume, castState.PillDosageLimit);

            PillTypeButtons[castState.SelectedPillType].Pressed = true;

            PillNumber.IsValid = x => x >= 0 && x <= pillNumberMax;
            PillDosage.IsValid = x => x > 0 && x <= castState.PillDosageLimit;
            BottleDosage.IsValid = x => x >= 0 && x <= bottleAmountMax;

            if (PillNumber.Value > pillNumberMax)
                PillNumber.Value = pillNumberMax;
            if (BottleDosage.Value > bottleAmountMax)
                BottleDosage.Value = bottleAmountMax;

            // Avoid division by zero
            if (PillDosage.Value > 0)
            {
                PillNumber.Value = Math.Min(bufferVolume / PillDosage.Value, pillNumberMax);
            }
            else
            {
                PillNumber.Value = 0;
            }

            BottleDosage.Value = Math.Min(bottleAmountMax, bufferVolume);
        }
        /// <summary>
        /// Generate a product label based on reagents in the buffer.
        /// </summary>
        /// <param name="state">State data sent by the server.</param>
        private string GenerateLabel(ChemMasterBoundUserInterfaceState state)
        {
            if (state.BufferCurrentVolume == 0)
                return "";

            var reagent = state.BufferReagents.OrderBy(r => r.Quantity).First().Reagent;
            _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
            return proto?.LocalizedName ?? "";
        }

        /// <summary>
        /// Update the container, buffer, and packaging panels.
        /// </summary>
        /// <param name="state">State data for the dispenser.</param>
        private void UpdatePanelInfo(ChemMasterBoundUserInterfaceState state)
        {
            BufferTransferButton.Pressed = state.Mode == ChemMasterMode.Transfer;
            BufferDiscardButton.Pressed = state.Mode == ChemMasterMode.Discard;

            UpdateContainerInfo(_inputReagentList, state.InputContainerInfo);
            UpdateContainerInfo(_outputReagentList, state.OutputContainerInfo);

            // This has to happen here due to people possibly
            // setting sorting before putting any chemicals
            BufferSortButton.Text = state.SortingType switch
            {
                ChemMasterSortingType.Alphabetical => Loc.GetString("chem-master-window-sort-type-alphabetical"),
                ChemMasterSortingType.Quantity => Loc.GetString("chem-master-window-sort-type-quantity"),
                ChemMasterSortingType.Latest => Loc.GetString("chem-master-window-sort-type-latest"),
                _ => Loc.GetString("chem-master-window-sort-type-none")
            };

            // Setting the sorting type triggers a rebuild of the rows, so we
            // set it to null if it hasn't changed.
            _bufferReagentList.Update(state.BufferReagents.ToDictionary(
                    r => new ReagentListEntry(r.Reagent, null),
                    r => r.Quantity),
                state.SortingType != _lastSortingType ? state.SortingType : null);

            _lastSortingType = state.SortingType;

            _bufferReagentList.UpdateLabels(null, ReagentQuantity.LocalizedQuantity(state.BufferCurrentVolume));
        }

        private void UpdateContainerInfo(ReagentList list, ContainerInfo? info)
        {
            // Having Entities versus Reagents is mutually exclusive
            // Technically the UI would display it fine, though.
            if (info?.Entities is { } entities)
            {
                list.Update(entities.ToDictionary(ent => new ReagentListEntry(null, ent.Id), ent => ent.Quantity));
            }
            else if (info?.Reagents is { } reagents)
            {
                list.Update(reagents.ToDictionary(r => new ReagentListEntry(r.Reagent, null), v => v.Quantity));
            }
            else
            {
                list.Update([]);
            }

            if (info is { DisplayName: var name })
                list.UpdateLabels($"{name}: ", info.LocalizedCapacity());
        }

        public string LabelLine
        {
            get => LabelLineEdit.Text;
            set => LabelLineEdit.Text = value;
        }
    }
}
