//
// Copyright (C) 1993-1996 Id Software, Inc.
// Copyright (C) 2019-2020 Nobuaki Tanaka
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//



using System;

namespace ManagedDoom
{
    public static partial class DoomInfo
    {
        public static readonly DoomString[] SpriteNames = new DoomString[]
        {
            new DoomString("TROO"),
            new DoomString("SHTG"),
            new DoomString("PUNG"),
            new DoomString("PISG"),
            new DoomString("PISF"),
            new DoomString("SHTF"),
            new DoomString("SHT2"),
            new DoomString("CHGG"),
            new DoomString("CHGF"),
            new DoomString("MISG"),
            new DoomString("MISF"),
            new DoomString("SAWG"),
            new DoomString("PLSG"),
            new DoomString("PLSF"),
            new DoomString("BFGG"),
            new DoomString("BFGF"),
            new DoomString("BLUD"),
            new DoomString("PUFF"),
            new DoomString("BAL1"),
            new DoomString("BAL2"),
            new DoomString("PLSS"),
            new DoomString("PLSE"),
            new DoomString("MISL"),
            new DoomString("BFS1"),
            new DoomString("BFE1"),
            new DoomString("BFE2"),
            new DoomString("TFOG"),
            new DoomString("IFOG"),
            new DoomString("PLAY"),
            new DoomString("POSS"),
            new DoomString("SPOS"),
            new DoomString("VILE"),
            new DoomString("FIRE"),
            new DoomString("FATB"),
            new DoomString("FBXP"),
            new DoomString("SKEL"),
            new DoomString("MANF"),
            new DoomString("FATT"),
            new DoomString("CPOS"),
            new DoomString("SARG"),
            new DoomString("HEAD"),
            new DoomString("BAL7"),
            new DoomString("BOSS"),
            new DoomString("BOS2"),
            new DoomString("SKUL"),
            new DoomString("SPID"),
            new DoomString("BSPI"),
            new DoomString("APLS"),
            new DoomString("APBX"),
            new DoomString("CYBR"),
            new DoomString("PAIN"),
            new DoomString("SSWV"),
            new DoomString("KEEN"),
            new DoomString("BBRN"),
            new DoomString("BOSF"),
            new DoomString("ARM1"),
            new DoomString("ARM2"),
            new DoomString("BAR1"),
            new DoomString("BEXP"),
            new DoomString("FCAN"),
            new DoomString("BON1"),
            new DoomString("BON2"),
            new DoomString("BKEY"),
            new DoomString("RKEY"),
            new DoomString("YKEY"),
            new DoomString("BSKU"),
            new DoomString("RSKU"),
            new DoomString("YSKU"),
            new DoomString("STIM"),
            new DoomString("MEDI"),
            new DoomString("SOUL"),
            new DoomString("PINV"),
            new DoomString("PSTR"),
            new DoomString("PINS"),
            new DoomString("MEGA"),
            new DoomString("SUIT"),
            new DoomString("PMAP"),
            new DoomString("PVIS"),
            new DoomString("CLIP"),
            new DoomString("AMMO"),
            new DoomString("ROCK"),
            new DoomString("BROK"),
            new DoomString("CELL"),
            new DoomString("CELP"),
            new DoomString("SHEL"),
            new DoomString("SBOX"),
            new DoomString("BPAK"),
            new DoomString("BFUG"),
            new DoomString("MGUN"),
            new DoomString("CSAW"),
            new DoomString("LAUN"),
            new DoomString("PLAS"),
            new DoomString("SHOT"),
            new DoomString("SGN2"),
            new DoomString("COLU"),
            new DoomString("SMT2"),
            new DoomString("GOR1"),
            new DoomString("POL2"),
            new DoomString("POL5"),
            new DoomString("POL4"),
            new DoomString("POL3"),
            new DoomString("POL1"),
            new DoomString("POL6"),
            new DoomString("GOR2"),
            new DoomString("GOR3"),
            new DoomString("GOR4"),
            new DoomString("GOR5"),
            new DoomString("SMIT"),
            new DoomString("COL1"),
            new DoomString("COL2"),
            new DoomString("COL3"),
            new DoomString("COL4"),
            new DoomString("CAND"),
            new DoomString("CBRA"),
            new DoomString("COL6"),
            new DoomString("TRE1"),
            new DoomString("TRE2"),
            new DoomString("ELEC"),
            new DoomString("CEYE"),
            new DoomString("FSKU"),
            new DoomString("COL5"),
            new DoomString("TBLU"),
            new DoomString("TGRN"),
            new DoomString("TRED"),
            new DoomString("SMBT"),
            new DoomString("SMGT"),
            new DoomString("SMRT"),
            new DoomString("HDB1"),
            new DoomString("HDB2"),
            new DoomString("HDB3"),
            new DoomString("HDB4"),
            new DoomString("HDB5"),
            new DoomString("HDB6"),
            new DoomString("POB1"),
            new DoomString("POB2"),
            new DoomString("BRS1"),
            new DoomString("TLMP"),
            new DoomString("TLP2")
        };
    }
}
