using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Shared.Kitchen.Components;
using Robust.Client.Graphics;

namespace Content.Client.Kitchen.UI;

[GenerateTypedNameReferences]
public sealed partial class MicrowaveMenu : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private const int CookTimeButtonCount = 6;
    private const int CookTimeStepSeconds = 5;
    private const int StyleBreakButtonIndex = 4;

    private static readonly StyleBoxFlat BusyStyle = new() { BackgroundColor = Color.FromHex("#947300") };
    private static readonly StyleBoxFlat IdleStyle = new() { BackgroundColor = Color.FromHex("#1B1B1E") };

    public event Action<int, uint>? OnCookTimeSelected;
    public event Action<NetEntity>? OnEjectSolid;

    private ButtonGroup CookTimeButtonGroup { get; }

    private bool _isBusy;
    private TimeSpan _currentCookTimeEnd;
    private uint? _lastSecondsUpdate;

    public MicrowaveMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        CookTimeButtonGroup = new ButtonGroup();
        InstantCookButton.Group = CookTimeButtonGroup;
        InstantCookButton.OnPressed += _ => OnCookTimeSelected?.Invoke(0, 0);

        for (var i = 1; i <= CookTimeButtonCount; i++)
        {
            var newButton = CreateCookTimeButton(i);
            CookTimeButtonGrid.AddChild(newButton);
        }
        UpdateTimerDisplay(0);
    }

    public void UpdateUi(MicrowaveUpdateUserInterfaceState state)
    {
        _isBusy = state.IsMicrowaveBusy;
        _currentCookTimeEnd = state.CurrentCookTimeEnd;

        DisableCookingPanelOverlay.Visible = state.IsMicrowaveBusy || state.ContainedSolids.Length == 0;

        IngredientGridHelper.PopulateIngredientsGrid(
            IngredientsGrid,
            _entityManager,
            state.ContainedSolids,
            netEntity => OnEjectSolid?.Invoke(netEntity),
            Loc.GetString("microwave-menu-ingredients-empty"));

        StartButton.Disabled = state.IsMicrowaveBusy || state.ContainedSolids.Length == 0;
        EjectButton.Disabled = state.IsMicrowaveBusy || state.ContainedSolids.Length == 0;

        UpdateTimerDisplay(state.CurrentCookTime);

        if (state.ActiveButtonIndex == 0)
        {
            InstantCookButton.Pressed = true;
        }
        else
        {
            var buttonIndex = state.ActiveButtonIndex - 1;
            if (buttonIndex >= 0 && buttonIndex < CookTimeButtonGrid.ChildCount)
            {
                ((Button) CookTimeButtonGrid.GetChild(buttonIndex)).Pressed = true;
            }
        }

        IngredientsPanel.PanelOverride = state is { IsMicrowaveBusy: true, ContainedSolids.Length: > 0 }
            ? BusyStyle
            : IdleStyle;
    }

    private Button CreateCookTimeButton(int index)
    {
        var cookTime = (uint) (index * CookTimeStepSeconds);
        var newButton = new Button
        {
            Text = cookTime.ToString(),
            TextAlign = Label.AlignMode.Center,
            ToggleMode = true,
            Group = CookTimeButtonGroup,
            HorizontalExpand = true,
        };
        newButton.StyleClasses.Add(index == StyleBreakButtonIndex ? "OpenRight" : "OpenBoth");
        newButton.OnPressed += _ => OnCookTimeSelected?.Invoke(index, cookTime);
        return newButton;
    }

    private void UpdateTimerDisplay(uint seconds)
    {
        if (_lastSecondsUpdate == seconds)
            return;

        _lastSecondsUpdate = seconds;
        var minutes = seconds / 60;
        var secs = seconds % 60;
        TimerDisplay.Text = $"{minutes:D2}:{secs:D2}";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_isBusy)
            return;

        var curTime = _timing.CurTime;
        if (_currentCookTimeEnd > curTime)
        {
            var remaining = (_currentCookTimeEnd - curTime).TotalSeconds;
            UpdateTimerDisplay((uint) Math.Ceiling(remaining));
        }
        else
        {
            UpdateTimerDisplay(0);
        }
    }
}
