using Content.Client.UserInterface.Controls;
using Content.Shared.Mining;
using Content.Shared.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;

namespace Content.Client.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class StationAiCustomizationMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;

    private readonly SharedStationAiSystem _stationAiSystem = default!;

    private EntityUid? _owner = null;
    private Dictionary<ProtoId<StationAiCustomizationGroupPrototype>, StationAiCustomizationGroupContainer> _groupContainers = new();

    public event Action<ProtoId<StationAiCustomizationGroupPrototype>, ProtoId<StationAiCustomizationPrototype>>? SendStationAiCustomizationMessageAction;

    public StationAiCustomizationMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _stationAiSystem = _entManager.System<SharedStationAiSystem>();

        Title = Loc.GetString("station-ai-customization-menu");

        var groupPrototypes = _protoManager.EnumeratePrototypes<StationAiCustomizationGroupPrototype>();
        groupPrototypes = groupPrototypes.OrderBy(x => x.ID); // To ensure consistency in presention

        foreach (var groupPrototype in groupPrototypes)
        {
            _groupContainers[groupPrototype] = new StationAiCustomizationGroupContainer(groupPrototype, _protoManager);
            CustomizationGroupsContainer.AddTab(_groupContainers[groupPrototype], Loc.GetString(groupPrototype.Name));
        }
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
        UpdateState();
    }

    public void UpdateState()
    {
        if (_owner == null || !_entManager.TryGetComponent<StationAiCoreComponent>(_owner, out var stationAiCore))
            return;

        if (!_stationAiSystem.TryGetInsertedAI((_owner.Value, stationAiCore), out var insertedAi))
            return;

        if (!_entManager.TryGetComponent<StationAiCustomizationComponent>(insertedAi, out var stationAiCustomization))
            return;

        foreach (var (groupProtoId, groupContainer) in _groupContainers)
        {
            if (stationAiCustomization.ProtoIds.TryGetValue(groupProtoId, out var protoId))
            {
                foreach (var child in groupContainer.Children)
                {
                    if (child is not StationAiCustomizationEntryContainer entry)
                        continue;

                    entry.SelectButton.Pressed = (entry.ProtoId == protoId);
                }
            }
        }
    }

    public void OnSendStationAiCustomizationMessage
        (ProtoId<StationAiCustomizationGroupPrototype> groupProtoId, ProtoId<StationAiCustomizationPrototype> customizationProtoId)
    {
        SendStationAiCustomizationMessageAction?.Invoke(groupProtoId, customizationProtoId);
    }

    private sealed class StationAiCustomizationGroupContainer : BoxContainer
    {
        public StationAiCustomizationGroupContainer(StationAiCustomizationGroupPrototype groupPrototype, IPrototypeManager protoManager)
        {
            Orientation = LayoutOrientation.Vertical;
            HorizontalExpand = true;
            VerticalExpand = true;

            foreach (var protoId in groupPrototype.ProtoIds)
            {
                if (!protoManager.TryIndex(protoId, out var prototype))
                    continue;

                var entry = new StationAiCustomizationEntryContainer(groupPrototype, prototype);
                AddChild(entry);
            }
        }
    }

    private sealed class StationAiCustomizationEntryContainer : BoxContainer
    {
        public ProtoId<StationAiCustomizationPrototype> ProtoId;
        public Button SelectButton;

        public StationAiCustomizationEntryContainer(StationAiCustomizationGroupPrototype groupPrototype, StationAiCustomizationPrototype prototype)
        {
            ProtoId = prototype;

            Orientation = LayoutOrientation.Horizontal;
            HorizontalExpand = true;

            SelectButton = new Button
            {
                Text = Loc.GetString(prototype.Name),
                HorizontalExpand = true,
                ToggleMode = true
            };

            SelectButton.OnPressed += args =>
            {
                SelectButton.Pressed = true;

                if (this.Parent == null)
                    return;

                foreach (var child in this.Parent.Children)
                {
                    if (child is not StationAiCustomizationEntryContainer entry)
                        continue;

                    if (entry == this)
                        continue;

                    entry.SelectButton.Pressed = false;
                }

                var parent = this.Parent;

                while (parent != null && parent is not StationAiCustomizationMenu)
                    parent = parent.Parent;

                (parent as StationAiCustomizationMenu)?.OnSendStationAiCustomizationMessage(groupPrototype, prototype);
            };

            AddChild(SelectButton);

            var icon = new AnimatedTextureRect
            {
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SetWidth = 56,
                SetHeight = 56,
                Margin = new Thickness(10f, 2f)
            };

            var rsiPath = prototype.LayerData[groupPrototype.PreviewKey].RsiPath;
            var rsiState = prototype.LayerData[groupPrototype.PreviewKey].State;

            if (rsiPath != null && rsiState != null)
            {
                var specifier = new SpriteSpecifier.Rsi(new ResPath(rsiPath), rsiState);
                icon.SetFromSpriteSpecifier(specifier);
            }

            icon.DisplayRect.TextureScale = new Vector2(1.75f, 1.75f);

            AddChild(icon);
        }
    }
}


