namespace Content.Shared.Database;

public enum AdminAuditAction
{
    Smite = 1,
    Kick = 2,
    Ban = 3,
    Unban = 4,
    RoleBan = 5,
    RoleUnban = 6,
    DepartmentBan = 7,
    Freeze = 8,
    Unfreeze = 9,
    Teleport = 10,
    Respawn = 11,
    SetRole = 12,
    ForceGhost = 13,
    Rejuvenate = 14,
    HealAll = 15,
    SetSpecies = 16,
    AdminMessage = 17,
    SetMind = 18,

    SpawnEntity = 20,
    DeleteEntity = 21,
    VVWrite = 22,
    SetOutfit = 23,
    ModifySolution = 24,
    ModifyAccess = 25,
    ModifyLaws = 26,
    ModifyTags = 27,
    CloneEntity = 28,
    ScaleEntity = 29,

    RestartRound = 40,
    EndRound = 41,
    StartRound = 42,
    ForceMap = 43,
    ForcePreset = 44,
    AddGameRule = 45,
    RemoveGameRule = 46,
    CallShuttle = 47,
    RecallShuttle = 48,
    ToggleLateJoin = 49,
    DelayRoundStart = 50,

    CvarChange = 60,
    SetMotd = 61,
    PanicBunkerToggle = 62,

    WhitelistAdd = 70,
    WhitelistRemove = 71,
    BlacklistAdd = 72,
    BlacklistRemove = 73,
    NoteCreate = 74,
    NoteEdit = 75,
    NoteDelete = 76,
    WatchlistCreate = 77,
    WatchlistEdit = 78,
    WatchlistDelete = 79,
    PermissionChange = 80,
    BanExemptionChange = 81,

    CreateVote = 90,
    CancelVote = 91,
    Announce = 92,

    PlacementCreate = 100,
    PlacementDelete = 101,
    TilePlacement = 102,

    AdminGhost = 110,
    DeAdmin = 111,
    ReAdmin = 112,
    StealthMode = 113,
    PromoteHost = 114,
    ControlMob = 115,
    Erase = 116,

    ToolshedCommand = 120,
    CommandExecution = 121,

    ResourceUpload = 130,
    PlayGlobalSound = 131,
}
