using Content.Shared.Lathe.Prototypes;
using Content.Shared.Research.Prototypes;
using Robust.Shared.Audio;
using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Timing;

namespace Content.Shared.Lathe.Components;

// TODO: FIELD DELTAS!!! Change all Dirties to FieldDeltas because Recipe churn is no joke!
[RegisterComponent, NetworkedComponent]
public sealed partial class LatheComponent : Component, IComponentDelta
{
    public GameTick LastUnclassifiedDirty { get; set; }

    public GameTick[] LastModifiedFields { get; set; } = default!;

    /// <summary>
    /// All of the recipe packs that the lathe has by default
    /// </summary>
    [DataField]
    public List<ProtoId<LatheRecipePackPrototype>> StaticPacks = new();

    /// <summary>
    /// All of the recipe packs that the lathe is capable of researching
    /// </summary>
    [DataField]
    public List<ProtoId<LatheRecipePackPrototype>> DynamicPacks = new();
    // Note that this shouldn't be modified dynamically.
    // I.e., this + the static recipies should represent all recipies that the lathe can ever make
    // Otherwise the material arbitrage test and/or LatheSystem.GetAllBaseRecipes needs to be updated

    /// <summary>
    /// All of the recipies this lathe currently has.
    /// </summary>
    [DataField]
    public List<ProtoId<LatheRecipePrototype>> Recipes = new();

    /// <summary>
    /// The lathe's construction queue.
    /// </summary>
    /// <remarks>
    /// This is a LinkedList to allow for constant time insertion/deletion (vs a List), and more efficient
    /// moves (vs a Queue).
    /// </remarks>
    [DataField]
    public LinkedList<LatheRecipeBatch> Queue = new();

    /// <summary>
    /// The sound that plays when the lathe is producing an item, if any
    /// </summary>
    [DataField]
    public SoundSpecifier? ProducingSound;

    [DataField]
    public string? ReagentOutputSlotId;

    /// <summary>
    /// The default amount that's displayed in the UI for selecting the print amount.
    /// </summary>
    [DataField]
    public int DefaultProductionAmount = 1;

    /// <summary>
    /// The recipe the lathe is currently producing
    /// </summary>
    [ViewVariables]
    public ProtoId<LatheRecipePrototype>? CurrentRecipe;

    #region MachineUpgrading
    /// <summary>
    /// A modifier that changes how long it takes to print a recipe
    /// </summary>
    [DataField]
    public float TimeMultiplier = 1;

    /// <summary>
    /// A modifier that changes how much of a material is needed to print a recipe
    /// </summary>
    [DataField]
    public float MaterialUseMultiplier = 1;
    #endregion
}

/// <remarks>
/// We manually network the component state as updating a lathe BUI is expensive so it's best to break it into chunks.
/// </remarks>
[Serializable, NetSerializable]
public sealed class LatheComponentDeltaState : IAutoGeneratedComponentDeltaState, IComponentDeltaState<LatheComponentState>
{
    public const int QueueIndex = 0;
    public const int CurrentRecipeIndex = 1;
    public const int RecipesIndex = 2;

    public ulong ChangedFields { get; set; }

    [NetworkedDeltaField(QueueIndex)]
    public LinkedList<LatheRecipeBatch> Queue = default!;

    [NetworkedDeltaField(CurrentRecipeIndex)]
    public ProtoId<LatheRecipePrototype>? CurrentRecipe;

    [NetworkedDeltaField(RecipesIndex)]
    public List<ProtoId<LatheRecipePrototype>> Recipes = default!;

    public void ApplyToFullState(LatheComponentState fullState)
    {
        if ((ChangedFields & (1UL << QueueIndex)) != 0)
            fullState.Queue = Queue;

        if ((ChangedFields & (1UL << CurrentRecipeIndex)) != 0)
            fullState.CurrentRecipe = CurrentRecipe;

        if ((ChangedFields & (1UL << RecipesIndex)) != 0)
            fullState.Recipes = Recipes;
    }

    public LatheComponentState CreateNewFullState(LatheComponentState fullState)
    {
        var copy = new LatheComponentState(fullState);
        ApplyToFullState(copy);
        return copy;
    }
}

[Serializable, NetSerializable]
public sealed class LatheComponentState() : ComponentState
{
    public ulong ChangedFields { get; set; }

    public List<ProtoId<LatheRecipePrototype>> Recipes = default!;

    public LinkedList<LatheRecipeBatch> Queue = default!;

    public ProtoId<LatheRecipePrototype>? CurrentRecipe;

    public LatheComponentState(LatheComponentState existing) : this()
    {
        Recipes = existing.Recipes;
        Queue = existing.Queue;
        CurrentRecipe = existing.CurrentRecipe;
    }
}
