name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: ${{ github.actor != vars.REPO_BOT_NAME }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
