name: Publish Testing

concurrency:
  group: publish-testing
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
  - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
        fetch-depth: 0
        filter: blob:none
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Update changelog
      run: |
        dotnet tool install --global SpaceWizards.ChangelogTool --version 1.0.7
        ss14-changelog update -d Resources/Changelog
      env:
        REPO: ${{ github.repository }}
        BRANCH: master
        CHANGELOG_REPO_PATH: Resources/Changelog
        EXTRA_CATEGORIES: Admin,Maps,Rules
        GITHUB_TOKEN: ${{ secrets.CL_ACCESS_TOKEN }}

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform win-arm64 --platform linux-x64 --platform linux-arm64 --platform osx-x64 --platform osx-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Publish version
      run: Tools/publish_multi_request.py --fork-id wizards-testing
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}

    - name: Publish changelog (RSS)
      continue-on-error: true
      run: Tools/actions_changelog_rss.py
      env:
        CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}

    - name: Get Previous Successful Run Commit
      id: get_commit
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref_name != 'master-publish-backup'
      run: |
        # Github doesn't support giving workflow filenames, despite needing it for the REST API. So we gotta regex it out.
        # Yes, there's a 4 year old issue for it... https://github.com/orgs/community/discussions/10052
        WORKFLOW_FILENAME=$(echo "${{ github.workflow_ref }}" | grep -oP '(?<=.github/workflows/)[^@]+')
        PREVIOUS_SHA=$(gh api \
          -H "Accept: application/vnd.github+json" \
          "/repos/${{ github.repository }}/actions/workflows/${WORKFLOW_FILENAME}/runs?branch=${{ github.ref_name }}&status=success&per_page=2" \
          --jq '.workflow_runs[0].head_sha')

        # If there is no previous run, .workflow_runs[1] will return null
        if [ "$PREVIOUS_SHA" = "null" ] || [ -z "$PREVIOUS_SHA" ]; then
          echo "No previous successful workflow run found."
          echo "update=false" >> $GITHUB_OUTPUT
        else
          echo "Found previous successful commit: $PREVIOUS_SHA"
          echo "update=true" >> $GITHUB_OUTPUT
          echo "sha=$PREVIOUS_SHA" >> $GITHUB_OUTPUT
        fi

    - name: Force Update Backup Branch
      if: steps.get_commit.outputs.update == 'true'
      run: |
        TARGET_BRANCH="master-publish-backup"
        COMMIT_SHA="${{ steps.get_commit.outputs.sha }}"

        git fetch origin $COMMIT_SHA --depth=1
        git checkout $COMMIT_SHA
        git commit --allow-empty -m "Backup separation commit"
        git push origin HEAD:refs/heads/$TARGET_BRANCH --force
